version: '3.8'

services:
  api:
    build: ./Api
    ports:
      - "5000:5000"
    volumes:
      - ./saved_model:/app/../saved_model
    environment:
      - FLASK_ENV=production

  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - API_URL=http://api:5000/predict
